#!/bin/sh

### BEGIN INIT INFO
# Provides:           snortd
# Required-Start:     $remote_fs $syslog
# Required-Stop:      $remote_fs $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Start Snort daemon at boot time
# Description:        Enable service provided by daemon
### END INIT INFO

# where the program resides that I want to start
DIR=/usr/local/bin
DAEMON=$DIR/snort
DAEMON_NAME=snortd

# command line options for my daemon
DAEMON_OPTS="-y -u snort -g snort -c /etc/snort/snort.conf"

# This line determines which user runs the script
# root not generally recommended, but necessary on the Pi
DAEMON_USER=root

# The process id of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

# this sources the pid or something like that (required)
. /lib/lsb/init-functions

do_start()
{
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}

do_stop()
{
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0

